# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
