# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0012_auto_20161217_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BdayApp.Event'),
        ),
    ]
