# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0018_auto_20170325_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='associated_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_wallet', to='BdayApp.Event'),
        ),
    ]
