# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0024_auto_20170423_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTestMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
