# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0025_filetestmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchat',
            name='type',
            field=models.CharField(default='LR', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filetestmode',
            name='char_field',
            field=models.CharField(default='TEST', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='eventchat',
            name='file_field',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='filetestmode',
            name='file_field',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
