# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0026_auto_20170428_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnreadChatBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BdayApp.Event')),
                ('last_read_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BdayApp.EventChat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BdayApp.BdayAppUser')),
            ],
        ),
    ]
