# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0004_auto_20161118_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdayappuser',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-creation_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-creation_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(null=True, related_name='members', to='BdayApp.BdayAppUser'),
        ),
    ]
