# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0007_auto_20161204_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('from_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_', to='BdayApp.BdayAppUser')),
                ('to_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_', to='BdayApp.BdayAppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('associated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BdayApp.BdayAppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField()),
                ('name', models.CharField(max_length=500)),
                ('website_name', models.CharField(max_length=500)),
                ('website_URL', models.URLField()),
                ('price', models.FloatField()),
                ('picture', models.URLField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
