# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0009_wish_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='created_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='URL',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='website_URL',
            new_name='website_url',
        ),
    ]
