# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0010_auto_20161213_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_field', models.CharField(max_length=100, null=True)),
                ('creation_date', models.DateTimeField()),
                ('url_field', models.URLField(null=True)),
                ('file_field', models.FilePathField(null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BdayApp.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BdayApp.BdayAppUser')),
                ('wish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BdayApp.Wish')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_privacy_field',
            field=models.CharField(choices=[('PUBLIC', 'PB'), ('PRIVATE', 'PV')], default='PV', max_length=10),
        ),
    ]
