# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0013_auto_20161218_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='type',
            field=models.CharField(default='FACEBOOK', max_length=50),
        ),
    ]
