# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0014_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_for',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_for', to='BdayApp.BdayAppUser'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(default='CUSTOM', max_length=50),
        ),
    ]
