# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0016_auto_20170428_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
