# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0018_auto_20170505_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
