# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0019_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='picture_file',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
