# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0021_auto_20170512_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchat',
            name='file_field',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
