# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0024_auto_20170708_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_privacy_field',
            new_name='contact_privacy_field',
        ),
    ]
