# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0025_auto_20170708_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherLifeEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_event', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('type', models.CharField(default='DEFAULT', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BdayApp.BdayAppUser')),
            ],
        ),
    ]
