# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdayApp', '0028_auto_20170709_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherlifeevents',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
